### ISSUE TITLE
linenumbers bug

### ISSUE THREAD

**Issue by glVertex** [faissaloo/L-nano#1]
**commit:**  ddf48b0
**exec:**
nano --linenumbers --softwrap
**playback bug:**
1. first line text is wider screen.
2. second line is random string.
3. go to end first line.
4. backspacing first line, until it fit one line
5. press Down.
**result:**
No changeable text in second line.
**PS:**
Maybe use the new ncurses window (like topwin or bottomwin) for the numbering of the lines?
+ use interface_color_pair \[LINE_NUMS\] (for example)
+ margin not necessary

**Comment by faissaloo** [comment]
I'm in the process of taking line numbers upstream where this issue has been fixed, a new release of GNU Nano with line numbers and the fix should be out next week:  
https://lists.gnu.org/archive/html/nano-devel/2016-10/msg00073.html
