### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by ErraticFox** [faissaloo/L-Nano#1]
Hello, when when I run through `make` I get this error: `nano.h:92:20: fatal error: curses.h: No such file or directory`

**Comment by faissaloo** [comment]
Do you have the ncurses headers installed? On ubuntu it's `sudo apt-get install libncurses-dev`

**Comment by ErraticFox** [comment]
That was it! I'm still new to Linux and compiling stuff, so sometimes I don't look through the error logs fully... :P
